// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package words

import (
	"star/api/words"
	usersL "star/internal/logic/users"
	wordsL "star/internal/logic/words"
)

type ControllerV1 struct {
	users *usersL.Users
	words *wordsL.Words
}

func NewV1() words.IWordsV1 {
	return &ControllerV1{
		users: &usersL.Users{},
		words: &wordsL.Words{},
	}
}
