// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package words

import (
	"star/api/words"
)

type ControllerV1 struct{}

func NewV1() words.IWordsV1 {
	return &ControllerV1{}
}
